// <auto-generated />
using ExampleEF.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExampleEF.Migrations
{
    [DbContext(typeof(Mycontext))]
    [Migration("20240121170013_inimig")]
    partial class inimig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExampleEF.Entity.Admin", b =>
                {
                    b.Property<int>("adminisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adminisId"));

                    b.Property<int>("cllgId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("adminisId");

                    b.HasIndex("cllgId");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("ExampleEF.Entity.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("College Name");

                    b.Property<int>("adminisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("colleges");
                });

            modelBuilder.Entity("ExampleEF.Entity.Admin", b =>
                {
                    b.HasOne("ExampleEF.Entity.College", "clg")
                        .WithMany()
                        .HasForeignKey("cllgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clg");
                });
#pragma warning restore 612, 618
        }
    }
}
